version: "3.9"
services:
  debian11-mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: deb
      MYSQL_PASSWORD: deb
      MYSQL_ROOT_PASSWORD: deb
      MYSQL_DATABASE: deb
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    profiles:
      - db
      - mysql
volumes:
  mysql: