---
- name: virtual host nginx
  block:
    - name: added virtual host file
      template:
        src: "{{ config }}"
        dest: /etc/nginx/conf.d/default.conf
      debugger: on_failed
      tags: add-virtual-host
    - name: reboot nginx
      service:
        name: nginx
        state: reloaded
      debugger: on_failed
      tags: nginx-reloaded
  tags: nginx-host

