---
- name: user management
  block:
    - name: create project user
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
      debugger: on_failed
      tags: create-project-user
    - name: change mode www-data user
      user:
        name: www-data
        groups: "{{ user_name }}"
      debugger: on_failed
      tags: change-mode-www-data
  tags: user