---
- name: u2004
  hosts: ubuntu2004
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mongodb
      tags: mongodb
    - role: pritunl
      tags: pritunl
    - role: mysql
      tags: mysql
- name: myserver
  hosts: myserver
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mysql
      tags: mysql
    - role: mysql-settings
      tags: mysql-settings
    - role: mysql-add-data
      tags: mysql-add-data
    - role: postgresql
      tags: postgresql
    - role: postgresql-settings
      tags: postgresql-settings
    - role: postgresql-add-data
      tags: postgresql-add-data
    - role: nodejs
      tags: nodejs
    - role: mongodb
      tags: mongodb
    - role: nginx
      tags: nginx