---
- name: u2004
  hosts: ubuntu2004
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mongodb
      tags: mongodb
    - role: pritunl
      tags: pritunl
    - role: mysql
      tags: mysql
- name: myserver
  hosts: myserver
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mysql
      tags: mysql
    - role: mysql-settings
      tags: mysql-settings