---
- name: u2004
  hosts: ubuntu2004
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mongodb
      tags: mongodb
    - role: pritunl
      tags: pritunl
    - role: mysql
      tags: mysql
- name: myserver
  hosts: myserver
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mysql
      tags: mysql
    - role: mysql-settings
      tags: mysql-settings
    - role: mysql-add-data
      tags: mysql-add-data
    - role: postgresql
      tags: postgresql
    - role: postgresql-settings
      tags: postgresql-settings
    - role: postgresql-add-data
      tags: postgresql-add-data
    - role: nodejs
      tags: nodejs
    - role: mongodb
      tags: mongodb
    - role: php
      tags: php
    - role: composer
      tags: composer
    - role: user
      tags: user
    - role: project
      tags: project
    - role: nginx
      tags: nginx
    - role: nginx-host
      tags: nginx-host
    - role: zabbix-agent
      tags: zabbix-agent
    - role: docker
      tags: docker
    - role: docker-compose
      tags: docker-compose
