---
- name: deploy
  hosts: ubuntu2004
  roles:
    - role: update
      tags: update
    - role: ufw
      tags: ufw
    - role: fail2ban
      tags: fail2ban
    - role: mongodb
      tags: mongodb
    - role: pritunl
      tags: pritunl