---
- name: install and settings docker
  block:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes
        state: present
      debugger: on_failed
      tags: docker-dependencies
    - name: added gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      debugger: on_failed
      tags: docker-add-gpg-key
    - name: set up a repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker
        update_cache: yes
      debugger: on_failed
      tags: add-repository
    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present
      debugger: on_failed
      tags: install-docker
    - name: Start docker on the boot
      systemd:
        name: docker
        state: started
        enabled: yes
      debugger: on_failed
      tags: start-docker-on-the-boot
  tags: docker