---
- name: added data for mysql
  block:
    - name: add user for mysql
      mysql_user:
        name: '{{ mysql_application_user }}'
        password: '{{ mysql_application_password }}'
        host: '%' # Разрешаем подключаться со всех хостов или localhost
        priv:
          '{{ mysql_application_db }}.*:ALL'
          #'*.*:USAGE'
          #'*.*:ALL,GRANT'
        state: present
      debugger: on_failed
      tags: add-application-mysql-user
    - name: add db for mysql
      mysql_db:
        name: '{{ mysql_application_db }}'
        state: present
        collation: 'utf8_general_ci'
        encoding: 'utf8'
      no_log: true
      debugger: on_failed
      tags: add-db-mysql
  #  - name: add grant all hosts
  #    community.mysql.mysql_query:
  #      query: "{{ item }}"
  #    with_items:
  #      - GRANT ALL PRIVILEGES ON `{{ mysql_application_db }}`.* TO `{{ mysql_application_user }}`@`%`
  #      - FLUSH PRIVILEGES;
  #    debugger: on_failed
  #    tags: add-grant-all-hosts
    - name: open port
      ufw:
        rule: allow
        port: 3306
        proto: tcp
        state: reloaded
      debugger: on_failed
      tags: add-mysql-port
  tags: mysql-add-data
